baseURL = "https://www.alexdarbyshire.com"
languageCode = "en-au"
title = "Alex Darbyshire"
theme = 'hugo-universal-theme'

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
disqusShortname = "alexdarbyshire"

enableRobotsTXT = true

# number of words of summarized post content (default 70)
summaryLength = 40

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[markup]
  [markup.tableOfContents]
    startLevel = 3
    endLevel = 3
    ordered = false

#Allow direct use of html and script in markdown (TODO: Be Hugo-onic and use shortcode instead)
[markup.goldmark.renderer]
  unsafe = true

[permalinks]
    posts = "/:year/:month/:slug/"
    page = "/:slug/"

[sitemap]
    changefreq = "weekly"
    priority = 0.5

# Enable Google Analytics by entering your tracking code
[services]
  [services.googleAnalytics]
     id = 'G-C05H5792C7'

#Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Posts"
    identifier = "menu.posts"
    url        = "/posts/"
    weight     = 2

[[menu.main]]
    name       = "Github"
    identifier = "menu.github"
    url        = "https://github.com/alexdarbyshire/alexdarbyshire.com"
    weight     = 3

#[[menu.main]]
#    name       = "Contact"
#    identifier = "menu.contact"
#    url        = "/contact/"
#    weight     = 4

[params]

# Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
style = "turquoise"

#about_us = "" 
copyright = "Copyright © 2024, Alex Darbyshire"

# Format dates with Go's time formatting
date_format = "January 2, 2006"

dropdown_mouse_over = false

disabled_logo = true
logo_text = "Alex Darbyshire"
#logo = "img/logo.png"
#logo_small = "img/logo-small.png"

[params.footer.recent_posts]
    enable = false

[params.recent_posts]
    enable = true
    title = "Welcome"
    subtitle = "A space for technology notes on anything I find interesting, and a musing or two. From electrons through to delivering and developing code, as well as shiny emerging tech."
   hide_summary = false

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true
